"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class initial_request(object):
    __slots__ = []

    __typenames__ = []

    __dimensions__ = []

    def __init__(self):
        pass

    def encode(self):
        buf = BytesIO()
        buf.write(initial_request._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        pass

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != initial_request._get_packed_fingerprint():
            raise ValueError("Decode error")
        return initial_request._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = initial_request()
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if initial_request in parents: return 0
        tmphash = (0x12345678) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if initial_request._packed_fingerprint is None:
            initial_request._packed_fingerprint = struct.pack(">Q", initial_request._get_hash_recursive([]))
        return initial_request._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

