"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class structNAVINFO(object):
    __slots__ = ["utmX", "utmY", "mLat", "mLon", "height", "mHeading", "mPitch", "mRoll", "mSpeed3d", "mSpeedX", "mSpeedY"]

    def __init__(self):
        self.utmX = 0.0
        self.utmY = 0.0
        self.mLat = 0.0
        self.mLon = 0.0
        self.height = 0.0
        self.mHeading = 0.0
        self.mPitch = 0.0
        self.mRoll = 0.0
        self.mSpeed3d = 0.0
        self.mSpeedX = 0.0
        self.mSpeedY = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(structNAVINFO._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddddddddddd", self.utmX, self.utmY, self.mLat, self.mLon, self.height, self.mHeading, self.mPitch, self.mRoll, self.mSpeed3d, self.mSpeedX, self.mSpeedY))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != structNAVINFO._get_packed_fingerprint():
            raise ValueError("Decode error")
        return structNAVINFO._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = structNAVINFO()
        self.utmX, self.utmY, self.mLat, self.mLon, self.height, self.mHeading, self.mPitch, self.mRoll, self.mSpeed3d, self.mSpeedX, self.mSpeedY = struct.unpack(">ddddddddddd", buf.read(88))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if structNAVINFO in parents: return 0
        tmphash = (0x8064363f723407ae) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if structNAVINFO._packed_fingerprint is None:
            structNAVINFO._packed_fingerprint = struct.pack(">Q", structNAVINFO._get_hash_recursive([]))
        return structNAVINFO._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

